
#ifndef _WSBUFFER_H
#define _WSBUFFER_H
//
// THE INFORMATION CONTAINED HEREIN IS PROVIDED <93>AS IS<94> AND NO PERSON OR ENTITY ASSOCIATED WITH THE
// INSTAQUOTE MARKET DATA API MAKES ANY REPRESENTATION OR WARRANTY, EXPRESS OR IMPLIED, AS TO THE
// INSTAQUOTE MARKET DATA API (OR THE RESULTS TO BE OBTAINED BY THE USE THEREOF) OR ANY OTHER MATTER
// AND EACH SUCH PERSON AND ENTITY SPECIFICALLY DISCLAIMS ANY WARRANTY OF ORIGINALITY, ACCURACY,
// COMPLETENESS, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  SUCH PERSONS AND ENTITIES
// DO NOT WARRANT THAT THE INSTAQUOTE MARKET DATA API WILL CONFORM TO ANY DESCRIPTION THEREOF OR
// BE FREE OF ERRORS.  THE ENTIRE RISK OF ANY USE OF THE INSTAQUOTE MARKET DATA API IS ASSUMED BY THE USER.
//
// NO PERSON OR ENTITY ASSOCIATED WITH THE INSTAQUOTE MARKET DATA API SHALL HAVE ANY LIABILITY FOR
// DAMAGE OF ANY KIND ARISING IN ANY MANNER OUT OF OR IN CONNECTION WITH ANY USER<92>S USE OF (OR ANY
// INABILITY TO USE) THE INSTAQUOTE MARKET DATA API, WHETHER DIRECT, INDIRECT, INCIDENTAL, SPECIAL
// OR CONSEQUENTIAL (INCLUDING, WITHOUT LIMITATION, LOSS OF DATA, LOSS OF USE, CLAIMS OF THIRD PARTIES
// OR LOST PROFITS OR REVENUES OR OTHER ECONOMIC LOSS), WHETHER IN TORT (INCLUDING NEGLIGENCE AND STRICT
// LIABILITY), CONTRACT OR OTHERWISE, WHETHER OR NOT ANY SUCH PERSON OR ENTITY HAS BEEN ADVISED OF,
// OR OTHERWISE MIGHT HAVE ANTICIPATED THE POSSIBILITY OF, SUCH DAMAGES.
//
// No proprietary or ownership interest of any kind is granted with respect to the INSTAQUOTE MARKET DATA API
// (or any rights therein).
//
// Copyright © 2009 Banc of America Securities, LLC. All rights reserved.
//
#pragma pack(push,8)

typedef struct tdBuffBlock
{
	char *Block;
	unsigned long Size;
	void *NextBuffBlock;
}BUFFBLOCK;

typedef struct tdBuffer
{
	char *Block;
	char *BlockStart;
    unsigned long BlockOffset;
	unsigned long Size;
	unsigned long LocalSize;
	unsigned long BlockSize;
	unsigned long MaxSize;
	BUFFBLOCK *TopBlock;
	BUFFBLOCK *BotBlock;
	int Busy;
}BUFFER;

WSAPILINK int WSOpenBuff(BUFFER *Buffer,int BlockSize);
WSAPILINK int WSOpenBuffLimit(BUFFER *Buffer,int BlockSize,int MaxSize);
WSAPILINK int WSCloseBuff(BUFFER *Buffer);
WSAPILINK int WSWriteBuff(BUFFER *Buffer,char *Source,int Length);
WSAPILINK int WSStripBuff(BUFFER *Buffer,int Length);

#pragma pack(pop)

#endif//_WSBUFFER_H
