//#define WS_DISPOFF
//#define WS_THE_EYE
//#define WS_WINDOWS_CE
//#define WS_LOGERRORS
//#define STATUS_UPDATE 1000
//#define BUFF_CHECK 100
//#define NO_OF_CON_PORTS 70
//#define WS_CON_TIMEOUT 6000
//#define WS_CONOUT_RECON 1000
//#define NO_OF_USC_PORTS 20
//#define NO_OF_USR_PORTS 1000
//#define WS_USR_TIMEOUT 6000
//#define WS_SENDS_PER_BEAT 70
//#define WS_TIMER_INTERVAL 9
//#define MAX_PENDING_CONNECTS 100  /* The backlog allowed for listen() */
//#define NO_FLAGS_SET         0  /* Used with recv()/send()          */
//#define WS_MSG_LENGTH       15 /* msg buffer sent back and forth   */
//#define WS_BLOCK_SIZE		16 /* size of buffer blocks */
//#define WS_USER				1000  /* Start of Wsocks defines */
//#define WS_LOG_MAX 500
//#define NO_OF_OTHER_PORTS 1000
//#define WS_MAX_DIALOGS (NO_OF_CON_PORTS+NO_OF_USR_PORTS+NO_OF_OTHER_PORTS)
//#define WS_COMPRESS
//#define WS_ENCRYPTED
//#define WS_MONITOR
//#define NO_OF_UMC_PORTS 1
//#define NO_OF_UMR_PORTS 10
//#define WS_UMR_TIMEOUT 600
//#define WS_NEW_DIALOGS
//#define WS_FILE_SERVER
//#define NO_OF_FILE_PORTS	4
//#define WS_FILE_TIMEOUT		6000
//#define FILE_XFERS_PER_TICK 16
//#define WS_CONCLOSE_ONCE
//#define NEW_BADDATES
//#undef NONPRO_VARSID
//#define WS_MONITOR
//#define HAVE_WSTRANSLATEUMRMSG
//#define WS_IPACL_DENY
//#define WS_DECLINING_RECONNECT
//
//#define NO_PORTS_CFG
//#define WS_GUARANTEED
//#define NO_OF_CGD_PORTS		10
//#define NO_OF_UGC_PORTS		10
//#define NO_OF_UGR_PORTS		10
//#define WS_CAST
//#define NO_OF_CTO_PORTS		10
//#define NO_OF_CTI_PORTS		10
//#define WS_CTO_TIMEOUT		6000
//#define WS_GETRTCOUNT
//#define WS_RETRY_LOG
